imports:
    - { resource: process/ }

clever_age_ui_process:
    logs:
        report_increment_level: Info # all logs higher are equal than Info were added to ProcessExecution report

clever_age_process:
    default_error_strategy: stop
    generic_transformers:
        uppercase:
            transformers:
                callback:
                    callback: strtoupper
        lowercase:
            transformers:
                callback:
                    callback: strtolower
        json_decode:
            transformers:
                callback:
                    callback: json_decode
                    right_parameters: [ true ] # $associative: When true, JSON objects will be returned as associative arrays
        substr:
            contextual_options:
                offset:
                    required: true
                length:
                    default_is_null: true
            transformers:
                callback:
                    callback: substr
                    right_parameters: [ '{{ offset }}', '{{ length }}' ]

