imports:
    - { resource: process/ }

clever_age_process_ui:
# Deprecated, @TODO Fix it
#    logs:
#        report_increment_level: Info # all logs higher are equal than Info were added to ProcessExecution report

clever_age_process:
    default_error_strategy: stop
    generic_transformers:
        uppercase:
            transformers:
                callback:
                    callback: strtoupper
        lowercase:
            transformers:
                callback:
                    callback: strtolower
