clever_age_process:
    configurations:
        demo.wiremock.get_json:
            description: >
                WireMock: GET a static JSON response, read from a body file (.docker/wiremock/mappings/books-list.json,
                __files/books.json), decode it and iterate over the books
            help: >
                Ex: bin/console cleverage:process:execute demo.wiremock.get_json
            tasks:
                request:
                    service: '@CleverAge\RestProcessBundle\Task\RequestTask'
                    options:
                        client: wiremock
                        url: '/books'
                        method: 'GET'
                    outputs: [ decode ]

                decode:
                    service: '@CleverAge\ProcessBundle\Task\TransformerTask'
                    options:
                        transformers:
                            json_decode: ~
                    outputs: [ iterate ]

                iterate:
                    service: '@CleverAge\ProcessBundle\Task\InputIteratorTask'
                    outputs: [ debug ]

                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
