clever_age_process:
    configurations:
        demo.logger:
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\Reporting\LoggerTask'
                    options:
                        level: warning
                        message: DEMO LOGGER
