clever_age_process:
    configurations:
        demo.file.csv_writer:
            description: >
                A simple process which write a csv
            help: >
                Ex: bin/console cleverage:process:execute demo.file.csv_writer
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\ConstantIterableOutputTask'
                    outputs: [ write ]
                    options:
                        output:
                            - column1: value1-1
                              column2: value2-1
                              column3: value3-1
                            - column1: value1-2
                              column2: value2-2
                              column3: value3-2
                            - column1: ''
                              column2: null
                              column3: value3-3
                write:
                    service: '@CleverAge\ProcessBundle\Task\File\Csv\CsvWriterTask'
                    options:
                        file_path: '%kernel.project_dir%/var/data/csv_writer_{date_time}.csv'
