clever_age_process:
    configurations:
        demo.upload_and_run:
            description: >
                A simple process which upload a csv file and read it to log/debug each line
            help: >
                Ex: bin/console cleverage:process:execute demo.upload_and_run --input=/path/to/file.csv -c delimiter:";"
            entry_point: entrypoint # for upload_and_run process entry_point is required
            options:
                ui:
                    source: Foo
                    target: Bar
                    entrypoint_type: file
                    default: ## set default values to UI launch form
                        #input: /var/wwww ###ignored because entrypoint_type is set to file
                        context:
                            - key: delimiter  # allow to change delimiter via UI form
                              value: ,
                    constraints: ## constraint to apply on the form
                        - Collection:
                              fields:
                                  input:
                                      - File: ~
                                  context:
                                      - Collection:
                                            fields:
                                                delimiter:
                                                    - Choice:
                                                          choices: [',', ';']
                                                          message: delimiter context must be , or ;. {{ value }} given.
            tasks:
                entrypoint: # Add log info to describe which file is reading
                    service: '@CleverAge\ProcessBundle\Task\Reporting\LoggerTask'
                    options:
                        message: Read file
                        level: info
                        context: [ 'input' ]
                    outputs: [ read ]
                read:
                    service: '@CleverAge\ProcessBundle\Task\File\Csv\InputCsvReaderTask'
                    outputs: [ log_line, dump ]
                    options:
                        delimiter: '{{ delimiter }}' ## delimiter is contextualized you must add -c delimiter:";" on console execute
                log_line:
                    service: '@CleverAge\ProcessBundle\Task\Reporting\LoggerTask'
                    options:
                        message: Read line
                        level: info
                        context: [ 'input' ]
                dump:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
