clever_age_process:
    configurations:
        demo.rest.post:
            description: >
                A simple process to use RestProcessBundle with POST method
            help: >
                Ex: bin/console cleverage:process:execute demo.rest.post
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\RestProcessBundle\Task\RequestTask'
                    error_strategy: 'stop'
                    options:
                        client: apicarto_ign
                        url: '/aoc/appellation-viticole'
                        method: 'POST'
                        data:
                            geom:
                                type: "Point"
                                coordinates: [-1.691634,48.104237]
                    outputs: [json_decode]
                json_decode:
                    service: '@CleverAge\ProcessBundle\Task\TransformerTask'
                    options:
                        transformers:
                            json_decode: ~
                    outputs: [debug]
                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
