clever_age_process:
    configurations:
        demo.sftp_purge:
            description: >
                A sample process to remove files from flysystem storage.
                filesystem context variable is used to define source filesystem.
                file_pattern context variable is used to define file_pattern to match.
                Following help show us how to delete all .csv files from filesystem remote.storage
                See config/packages/flysystem.yaml to see configured flysystem/storages.
            help: >
                bin/console cleverage:process:execute demo.sftp_purge -c filesystem:remote.storage -c file_pattern:/.csv$/ -vv
            options:
                ui:
                    source: Bar
                    target: Foo
                    ui_launch_mode: form
                    default: ## set default values to UI launch form
                        context:
                            - key: filesystem  # allow to change delimiter via UI form
                              value: 'remote.storage'
                            - key: file_pattern  # allow to change delimiter via UI form
                              value: '/.csv$/'
                    constraints: ## constraint to apply on the form
                        - Collection:
                              fields:
                                  input: ~
                                  context:
                                      - Collection:
                                            fields:
                                                filesystem:
                                                    - Choice:
                                                          choices: [ 'remote.storage', 'local.storage' ]
                                                file_pattern:
                                                    - NotBlank: ~

            tasks:
                get_files:
                    service: '@CleverAge\FlysystemProcessBundle\Task\ListContentTask'
                    description: >
                        List .csv files from remote.storage.
                        See config/packages/flysystem.yaml to see configured flysystem/storages.
                    outputs: get_file_path
                    options:
                        filesystem: '{{ filesystem }}'
                        file_pattern: '{{ file_pattern }}'
                get_file_path:
                    service: '@CleverAge\ProcessBundle\Task\PropertyGetterTask'
                    description: >
                        Get filepath within flysystem/storage.
                    outputs: remove
                    options:
                        property: 'path'
                remove:
                    service: '@CleverAge\FlysystemProcessBundle\Task\RemoveFileTask'
                    options:
                        filesystem: 'remote.storage'
