clever_age_process:
    configurations:
        demo.doctrine.update:
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\DoctrineProcessBundle\Task\Database\DatabaseUpdaterTask'
                    options:
                        sql: 'update process_user set firstname = :firstname, lastname = :lastname'
                        input_as_params: false
                        params:
                            firstname: Paul
                            lastname: Durand
                    outputs: [debug]

                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
