clever_age_process:
    configurations:
        demo.doctrine.entitymanager.reader_clearer:
            description: >
                A simple process to use DoctrineProcessBundle as entity reader (then clear the entitymanager)
            help: >
                Ex: bin/console cleverage:process:execute demo.doctrine.entitymanager.reader_clear
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\DoctrineProcessBundle\Task\EntityManager\DoctrineReaderTask'
                    options:
                        class_name: 'App\Entity\Author'
                        criteria:
                            lastname: 'King'
                        order_by:
                          lastname: 'asc'
                    outputs: [dump]

                dump:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
                    outputs: [clear]

                clear:
                    service: '@CleverAge\DoctrineProcessBundle\Task\EntityManager\ClearEntityManagerTask'
