clever_age_process:
    configurations:
        demo.file.file_reader:
            description: >
                A sample process to read a file from local storage and debug content
            help: >
                bin/console cleverage:process:execute demo.file.file_reader
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\File\FileReaderTask'
                    options:
                        filename: '%kernel.project_dir%/var/data/sample.txt'
                    outputs: debug
                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
