clever_age_process:
    configurations:
        demo.error_forwarder:
            description: >
                A simple process which forward data to an error output
            help: >
                Ex: bin/console cleverage:process:execute demo.error_forwarder
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\ConstantIterableOutputTask'
                    options:
                        output:
                            error1: Error 1
                            error2: Error 2
                            error3: Error 3
                    outputs: [ error_forwarder ]
                error_forwarder:
                    service: '@CleverAge\ProcessBundle\Task\Debug\ErrorForwarderTask'
