clever_age_process:
    configurations:
        demo.file.input_line_reader:
            description: >
                A simple process which read all files from a specific directory to log/debug each line
            help: >
                bin/console cleverage:process:execute demo.file.input_line_reader
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\File\FolderBrowserTask'
                    options:
                        folder_path: '%kernel.project_dir%/var/data'
                    outputs: read
                read:
                    service: '@CleverAge\ProcessBundle\Task\File\InputLineReaderTask'
                    outputs: [ log_line, dump ]
                log_line:
                    service: '@CleverAge\ProcessBundle\Task\Reporting\LoggerTask'
                    options:
                        message: Read line
                        level: info
                dump:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
