clever_age_process:
    configurations:
        demo.transformers_edge.slugify:
            description: >
                SlugifyTransformer with an invalid transliterator identifier
            help: >
                Ex: bin/console cleverage:process:execute demo.transformers_edge.slugify
            tasks:
                extract:
                    service: '@CleverAge\ProcessBundle\Task\ConstantOutputTask'
                    options:
                        output: 'Hélène Dupont'
                    outputs: [ transform ]
                transform:
                    service: '@CleverAge\ProcessBundle\Task\TransformerTask'
                    options:
                        transformers:
                            slugify:
                                transliterator: 'Not-A-Real-Transliterator'
                    outputs: [ debug ]
                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
