clever_age_process:
    configurations:
        demo.dummy:
            description: >
                A simple process with multiple output
            help: >
                Ex: bin/console cleverage:process:execute demo.dummy
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\ProcessBundle\Task\DummyTask'
                    outputs: [ output1, output2 ]
                output1:
                    service: '@CleverAge\ProcessBundle\Task\ConstantOutputTask'
                    options:
                        output:
                            id: 123
                            firstname: Test1
                            lastname: Test2
                    outputs: [ debug ]
                output2:
                    service: '@CleverAge\ProcessBundle\Task\ConstantOutputTask'
                    options:
                        output:
                            id: 456
                            firstname: Test3
                            lastname: Test4
                    outputs: [ debug ]
                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
