clever_age_process:
    configurations:
        demo.sample:
            description: >
                A simple process which transform data
            help: >
                Ex: bin/console cleverage:process:execute demo.transformer
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                extract:
                    service: '@CleverAge\ProcessBundle\Task\ConstantOutputTask'
                    options:
                        output:
                            id: 123
                            firstname: My Firstname
                            lastname: My Lastname
                    outputs: [ transform ]
                
                transform:
                    service: '@CleverAge\ProcessBundle\Task\TransformerTask'
                    options:
                        transformers:
                            mapping:
                                mapping:
                                    id:
                                        code: '[id]'
                                    slug:
                                        code:
                                            - '[id]'
                                            - '[firstname]'
                                            - '[lastname]'
                                        transformers: # 1st concat, 2nd slugify the result of 1st
                                            implode:
                                                separator: '-'
                                            slugify: ~
                                    firstname:
                                        code: '[firstname]'
                                        transformers:
                                            uppercase: ~ # see config/packages/cleverage_process.yaml for generic transformers definitions
                                    lastname:
                                        code: '[lastname]'
                                        transformers:
                                            uppercase: ~ # see config/packages/cleverage_process.yaml for generic transformers definitions
                    outputs: [ load, log ]
                log:
                    service: '@CleverAge\ProcessBundle\Task\Reporting\LoggerTask'
                    options:
                        message: Transformed
                        level: info
                load:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
