clever_age_process:
    configurations:
        demo.doctrine.read:
            description: >
                A simple process to use DoctrineProcessBundle as database reader
            help: >
                Ex: bin/console cleverage:process:execute demo.doctrine.read
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\DoctrineProcessBundle\Task\Database\DatabaseReaderTask'
                    options:
                        table: 'process_user'
                    outputs: [debug]

                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'
