clever_age_process:
    configurations:
        demo.doctrine.entitymanager.reader:
            description: >
                A simple process to use DoctrineProcessBundle as entity reader
            help: >
                Ex: bin/console cleverage:process:execute demo.doctrine.entitymanager.reader
            options:
                ui:
                    source: Bar
                    target: Foo
            tasks:
                entry:
                    service: '@CleverAge\DoctrineProcessBundle\Task\EntityManager\DoctrineReaderTask'
                    options:
                        class_name: 'App\Entity\Author'
                        criteria:
                            lastname: 'King'
                        order_by:
                          lastname: 'asc'
                    outputs: [debug]

                debug:
                    service: '@CleverAge\ProcessBundle\Task\Debug\DebugTask'