x-base-php: &base-php
  build:
    context: php
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      PHP_VERSION: ${PHP_VERSION:-8.2}
      XDEBUG_VERSION: ${XDEBUG_VERSION:-3.2.0}
  env_file: .env
  volumes:
    - ../:/var/www
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    COMPOSER_HOME: /var/www/.composer
    COMPOSER_MEMORY_LIMIT: -1
    XDEBUG_MODE: ${XDEBUG_MODE:-off}
    PHP_IDE_CONFIG: serverName=sandbox_symfony
    XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}

x-base-apache2: &base-apache2
  build:
    context: apache2
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
  env_file: .env
  volumes:
    - ../:/var/www
    - ./apache2/conf/apache2.conf:/etc/apache2/sites-available/000-default.conf
  depends_on:
    - php

x-base-mysql: &base-mysql
  build:
    context: mysql
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      MYSQL_VERSION: ${MYSQL_VERSION:-9.1.0}
  env_file: .env
  volumes:
    - process_bundle_demo_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app
    MYSQL_USER: app
    MYSQL_PASSWORD: app

name: cleverage-process-bundle-demo

services:
  php:
    <<: *base-php
    tty: true
    depends_on:
      mysql:
        condition: service_healthy

  apache2:
    <<: *base-apache2
    tty: true
    ports:
      - "${HTTP_PORT:-80}:80"

  mysql:
    <<: *base-mysql
    tty: true
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 100
    ports:
      - "${MYSQL_PORT:-3306}:3306"
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftp:/home/sftp/
    ports:
      - "22:22"
    command: sftp:password:1000

volumes:
  process_bundle_demo_data: