x-base-php: &base-php
  build:
    context: ./php
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      PHP_VERSION: ${PHP_VERSION:-8.2}
      XDEBUG_VERSION: ${XDEBUG_VERSION:-3.2.0}
  env_file: .env
  volumes:
    - ../:${VOLUME_ROOT:-/var/www/html}
    - ./php/ini/symfony.ini:/usr/local/etc/php/conf.d/99-symfony.ini
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    COMPOSER_HOME: ${VOLUME_ROOT:-/var/www/html}/.composer
    COMPOSER_MEMORY_LIMIT: -1
    XDEBUG_MODE: ${XDEBUG_MODE:-off}
    PHP_IDE_CONFIG: serverName=sandbox_symfony
    XDEBUG_CONFIG: ${XDEBUG_CONFIG:-}

x-base-apache2: &base-apache2
  build:
    context: ./apache2
    args:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
  env_file: .env
  volumes:
    - ../:${VOLUME_ROOT:-/var/www/html}
    - ./apache2/conf/apache2.conf:/etc/apache2/sites-available/000-default.conf
  depends_on:
    - php

name: cleverage-process-bundle-demo

services:
  php:
    <<: *base-php
    tty: true

  apache2:
    <<: *base-apache2
    tty: true
    ports:
      - "${HTTP_PORT:-80}:80"
